using System.Collections.Generic;

namespace iHentai.Controls
{
    public partial class Icon
    {
        public static Dictionary<Icons, string> Mapper { get; } = new Dictionary<Icons, string>
        {
            {Icons.GlobalNavigationButton, "\uE700"},
            {Icons.Wifi, "\uE701"},
            {Icons.Bluetooth, "\uE702"},
            {Icons.Connect, "\uE703"},
            {Icons.InternetSharing, "\uE704"},
            {Icons.VPN, "\uE705"},
            {Icons.Brightness, "\uE706"},
            {Icons.MapPin, "\uE707"},
            {Icons.QuietHours, "\uE708"},
            {Icons.Airplane, "\uE709"},
            {Icons.Tablet, "\uE70A"},
            {Icons.QuickNote, "\uE70B"},
            {Icons.RememberedDevice, "\uE70C"},
            {Icons.ChevronDown, "\uE70D"},
            {Icons.ChevronUp, "\uE70E"},
            {Icons.Edit, "\uE70F"},
            {Icons.Add, "\uE710"},
            {Icons.Cancel, "\uE711"},
            {Icons.More, "\uE712"},
            {Icons.Settings, "\uE713"},
            {Icons.Video, "\uE714"},
            {Icons.Mail, "\uE715"},
            {Icons.People, "\uE716"},
            {Icons.Phone, "\uE717"},
            {Icons.Pin, "\uE718"},
            {Icons.Shop, "\uE719"},
            {Icons.Stop, "\uE71A"},
            {Icons.Link, "\uE71B"},
            {Icons.Filter, "\uE71C"},
            {Icons.AllApps, "\uE71D"},
            {Icons.Zoom, "\uE71E"},
            {Icons.ZoomOut, "\uE71F"},
            {Icons.Microphone, "\uE720"},
            {Icons.Search, "\uE721"},
            {Icons.Camera, "\uE722"},
            {Icons.Attach, "\uE723"},
            {Icons.Send, "\uE724"},
            {Icons.SendFill, "\uE725"},
            {Icons.WalkSolid, "\uE726"},
            {Icons.InPrivate, "\uE727"},
            {Icons.FavoriteList, "\uE728"},
            {Icons.PageSolid, "\uE729"},
            {Icons.Forward, "\uE72A"},
            {Icons.Back, "\uE72B"},
            {Icons.Refresh, "\uE72C"},
            {Icons.Share, "\uE72D"},
            {Icons.Lock, "\uE72E"},
            {Icons.ReportHacked, "\uE730"},
            {Icons.FavoriteStar, "\uE734"},
            {Icons.FavoriteStarFill, "\uE735"},
            {Icons.Remove, "\uE738"},
            {Icons.Checkbox, "\uE739"},
            {Icons.CheckboxComposite, "\uE73A"},
            {Icons.CheckboxFill, "\uE73B"},
            {Icons.CheckboxIndeterminate, "\uE73C"},
            {Icons.CheckboxCompositeReversed, "\uE73D"},
            {Icons.CheckMark, "\uE73E"},
            {Icons.BackToWindow, "\uE73F"},
            {Icons.FullScreen, "\uE740"},
            {Icons.ResizeTouchLarger, "\uE741"},
            {Icons.ResizeTouchSmaller, "\uE742"},
            {Icons.ResizeMouseSmall, "\uE743"},
            {Icons.ResizeMouseMedium, "\uE744"},
            {Icons.ResizeMouseWide, "\uE745"},
            {Icons.ResizeMouseTall, "\uE746"},
            {Icons.ResizeMouseLarge, "\uE747"},
            {Icons.SwitchUser, "\uE748"},
            {Icons.Print, "\uE749"},
            {Icons.Up, "\uE74A"},
            {Icons.Down, "\uE74B"},
            {Icons.OEM, "\uE74C"},
            {Icons.Delete, "\uE74D"},
            {Icons.Save, "\uE74E"},
            {Icons.Mute, "\uE74F"},
            {Icons.BackSpaceQWERTY, "\uE750"},
            {Icons.ReturnKey, "\uE751"},
            {Icons.UpArrowShiftKey, "\uE752"},
            {Icons.Cloud, "\uE753"},
            {Icons.Flashlight, "\uE754"},
            {Icons.RotationLock, "\uE755"},
            {Icons.CommandPrompt, "\uE756"},
            {Icons.SIPMove, "\uE759"},
            {Icons.SIPUndock, "\uE75A"},
            {Icons.SIPRedock, "\uE75B"},
            {Icons.EraseTool, "\uE75C"},
            {Icons.UnderscoreSpace, "\uE75D"},
            {Icons.GripperTool, "\uE75E"},
            {Icons.Dialpad, "\uE75F"},
            {Icons.PageLeft, "\uE760"},
            {Icons.PageRight, "\uE761"},
            {Icons.MultiSelect, "\uE762"},
            {Icons.KeyboardLeftHanded, "\uE763"},
            {Icons.KeyboardRightHanded, "\uE764"},
            {Icons.KeyboardClassic, "\uE765"},
            {Icons.KeyboardSplit, "\uE766"},
            {Icons.Volume, "\uE767"},
            {Icons.Play, "\uE768"},
            {Icons.Pause, "\uE769"},
            {Icons.ChevronLeft, "\uE76B"},
            {Icons.ChevronRight, "\uE76C"},
            {Icons.InkingTool, "\uE76D"},
            {Icons.Emoji2, "\uE76E"},
            {Icons.GripperBarHorizontal, "\uE76F"},
            {Icons.System, "\uE770"},
            {Icons.Personalize, "\uE771"},
            {Icons.Devices, "\uE772"},
            {Icons.SearchAndApps, "\uE773"},
            {Icons.Globe, "\uE774"},
            {Icons.TimeLanguage, "\uE775"},
            {Icons.EaseOfAccess, "\uE776"},
            {Icons.UpdateRestore, "\uE777"},
            {Icons.HangUp, "\uE778"},
            {Icons.ContactInfo, "\uE779"},
            {Icons.Unpin, "\uE77A"},
            {Icons.Contact, "\uE77B"},
            {Icons.Memo, "\uE77C"},
            {Icons.Paste, "\uE77F"},
            {Icons.PhoneBook, "\uE780"},
            {Icons.LEDLight, "\uE781"},
            {Icons.Error, "\uE783"},
            {Icons.GripperBarVertical, "\uE784"},
            {Icons.Unlock, "\uE785"},
            {Icons.Slideshow, "\uE786"},
            {Icons.Calendar, "\uE787"},
            {Icons.GripperResize, "\uE788"},
            {Icons.Megaphone, "\uE789"},
            {Icons.Trim, "\uE78A"},
            {Icons.NewWindow, "\uE78B"},
            {Icons.SaveLocal, "\uE78C"},
            {Icons.Color, "\uE790"},
            {Icons.DataSense, "\uE791"},
            {Icons.SaveAs, "\uE792"},
            {Icons.Light, "\uE793"},
            {Icons.AspectRatio, "\uE799"},
            {Icons.DataSenseBar, "\uE7A5"},
            {Icons.Redo, "\uE7A6"},
            {Icons.Undo, "\uE7A7"},
            {Icons.Crop, "\uE7A8"},
            {Icons.OpenWith, "\uE7AC"},
            {Icons.Rotate, "\uE7AD"},
            {Icons.SetlockScreen, "\uE7B5"},
            {Icons.MapPin2, "\uE7B7"},
            {Icons.Package, "\uE7B8"},
            {Icons.Warning, "\uE7BA"},
            {Icons.ReadingList, "\uE7BC"},
            {Icons.Education, "\uE7BE"},
            {Icons.ShoppingCart, "\uE7BF"},
            {Icons.Train, "\uE7C0"},
            {Icons.Flag, "\uE7C1"},
            {Icons.Page, "\uE7C3"},
            {Icons.Multitask, "\uE7C4"},
            {Icons.BrowsePhotos, "\uE7C5"},
            {Icons.HalfStarLeft, "\uE7C6"},
            {Icons.HalfStarRight, "\uE7C7"},
            {Icons.Record, "\uE7C8"},
            {Icons.TouchPointer, "\uE7C9"},
            {Icons.LangJPN, "\uE7DE"},
            {Icons.Ferry, "\uE7E3"},
            {Icons.Highlight, "\uE7E6"},
            {Icons.ActionCenterNotification, "\uE7E7"},
            {Icons.PowerButton, "\uE7E8"},
            {Icons.ResizeTouchNarrower, "\uE7EA"},
            {Icons.ResizeTouchShorter, "\uE7EB"},
            {Icons.DrivingMode, "\uE7EC"},
            {Icons.RingerSilent, "\uE7ED"},
            {Icons.OtherUser, "\uE7EE"},
            {Icons.Admin, "\uE7EF"},
            {Icons.CC, "\uE7F0"},
            {Icons.SDCard, "\uE7F1"},
            {Icons.CallForwarding, "\uE7F2"},
            {Icons.SettingsDisplaySound, "\uE7F3"},
            {Icons.TVMonitor, "\uE7F4"},
            {Icons.Speakers, "\uE7F5"},
            {Icons.Headphone, "\uE7F6"},
            {Icons.DeviceLaptopPic, "\uE7F7"},
            {Icons.DeviceLaptopNoPic, "\uE7F8"},
            {Icons.DeviceMonitorRightPic, "\uE7F9"},
            {Icons.DeviceMonitorLeftPic, "\uE7FA"},
            {Icons.DeviceMonitorNoPic, "\uE7FB"},
            {Icons.Game, "\uE7FC"},
            {Icons.HorizontalTabKey, "\uE7FD"},
            {Icons.StreetsideSplitMinimize, "\uE802"},
            {Icons.StreetsideSplitExpand, "\uE803"},
            {Icons.Car, "\uE804"},
            {Icons.Walk, "\uE805"},
            {Icons.Bus, "\uE806"},
            {Icons.TiltUp, "\uE809"},
            {Icons.TiltDown, "\uE80A"},
            {Icons.RotateMapRight, "\uE80C"},
            {Icons.RotateMapLeft, "\uE80D"},
            {Icons.Home, "\uE80F"},
            {Icons.ParkingLocation, "\uE811"},
            {Icons.MapCompassTop, "\uE812"},
            {Icons.MapCompassBottom, "\uE813"},
            {Icons.IncidentTriangle, "\uE814"},
            {Icons.Touch, "\uE815"},
            {Icons.MapDirections, "\uE816"},
            {Icons.StartPoint, "\uE819"},
            {Icons.StopPoint, "\uE81A"},
            {Icons.EndPoint, "\uE81B"},
            {Icons.History, "\uE81C"},
            {Icons.Location, "\uE81D"},
            {Icons.MapLayers, "\uE81E"},
            {Icons.Accident, "\uE81F"},
            {Icons.Work, "\uE821"},
            {Icons.Construction, "\uE822"},
            {Icons.Recent, "\uE823"},
            {Icons.Bank, "\uE825"},
            {Icons.DownloadMap, "\uE826"},
            {Icons.InkingToolFill2, "\uE829"},
            {Icons.HighlightFill2, "\uE82A"},
            {Icons.EraseToolFill, "\uE82B"},
            {Icons.EraseToolFill2, "\uE82C"},
            {Icons.Dictionary, "\uE82D"},
            {Icons.DictionaryAdd, "\uE82E"},
            {Icons.ToolTip, "\uE82F"},
            {Icons.ChromeBack, "\uE830"},
            {Icons.ProvisioningPackage, "\uE835"},
            {Icons.AddRemoteDevice, "\uE836"},
            {Icons.Ethernet, "\uE839"},
            {Icons.ShareBroadband, "\uE83A"},
            {Icons.DirectAccess, "\uE83B"},
            {Icons.DialUp, "\uE83C"},
            {Icons.DefenderApp, "\uE83D"},
            {Icons.BatteryCharging9, "\uE83E"},
            {Icons.Battery10, "\uE83F"},
            {Icons.Pinned, "\uE840"},
            {Icons.PinFill, "\uE841"},
            {Icons.PinnedFill, "\uE842"},
            {Icons.PeriodKey, "\uE843"},
            {Icons.PuncKey, "\uE844"},
            {Icons.RevToggleKey, "\uE845"},
            {Icons.RightArrowKeyTime1, "\uE846"},
            {Icons.RightArrowKeyTime2, "\uE847"},
            {Icons.LeftQuote, "\uE848"},
            {Icons.RightQuote, "\uE849"},
            {Icons.DownShiftKey, "\uE84A"},
            {Icons.UpShiftKey, "\uE84B"},
            {Icons.PuncKey0, "\uE84C"},
            {Icons.PuncKeyLeftBottom, "\uE84D"},
            {Icons.RightArrowKeyTime3, "\uE84E"},
            {Icons.RightArrowKeyTime4, "\uE84F"},
            {Icons.Battery0, "\uE850"},
            {Icons.Battery1, "\uE851"},
            {Icons.Battery2, "\uE852"},
            {Icons.Battery3, "\uE853"},
            {Icons.Battery4, "\uE854"},
            {Icons.Battery5, "\uE855"},
            {Icons.Battery6, "\uE856"},
            {Icons.Battery7, "\uE857"},
            {Icons.Battery8, "\uE858"},
            {Icons.Battery9, "\uE859"},
            {Icons.BatteryCharging0, "\uE85A"},
            {Icons.BatteryCharging1, "\uE85B"},
            {Icons.BatteryCharging2, "\uE85C"},
            {Icons.BatteryCharging3, "\uE85D"},
            {Icons.BatteryCharging4, "\uE85E"},
            {Icons.BatteryCharging5, "\uE85F"},
            {Icons.BatteryCharging6, "\uE860"},
            {Icons.BatteryCharging7, "\uE861"},
            {Icons.BatteryCharging8, "\uE862"},
            {Icons.BatterySaver0, "\uE863"},
            {Icons.BatterySaver1, "\uE864"},
            {Icons.BatterySaver2, "\uE865"},
            {Icons.BatterySaver3, "\uE866"},
            {Icons.BatterySaver4, "\uE867"},
            {Icons.BatterySaver5, "\uE868"},
            {Icons.BatterySaver6, "\uE869"},
            {Icons.BatterySaver7, "\uE86A"},
            {Icons.BatterySaver8, "\uE86B"},
            {Icons.SignalBars1, "\uE86C"},
            {Icons.SignalBars2, "\uE86D"},
            {Icons.SignalBars3, "\uE86E"},
            {Icons.SignalBars4, "\uE86F"},
            {Icons.SignalBars5, "\uE870"},
            {Icons.SignalNotConnected, "\uE871"},
            {Icons.Wifi1, "\uE872"},
            {Icons.Wifi2, "\uE873"},
            {Icons.Wifi3, "\uE874"},
            {Icons.SIMLock, "\uE875"},
            {Icons.SIMMissing, "\uE876"},
            {Icons.Vibrate, "\uE877"},
            {Icons.RoamingInternational, "\uE878"},
            {Icons.RoamingDomestic, "\uE879"},
            {Icons.CallForwardInternational, "\uE87A"},
            {Icons.CallForwardRoaming, "\uE87B"},
            {Icons.JpnRomanji, "\uE87C"},
            {Icons.JpnRomanjiLock, "\uE87D"},
            {Icons.JpnRomanjiShift, "\uE87E"},
            {Icons.JpnRomanjiShiftLock, "\uE87F"},
            {Icons.StatusDataTransfer, "\uE880"},
            {Icons.StatusDataTransferVPN, "\uE881"},
            {Icons.StatusDualSIM2, "\uE882"},
            {Icons.StatusDualSIM2VPN, "\uE883"},
            {Icons.StatusDualSIM1, "\uE884"},
            {Icons.StatusDualSIM1VPN, "\uE885"},
            {Icons.StatusSGLTE, "\uE886"},
            {Icons.StatusSGLTECell, "\uE887"},
            {Icons.StatusSGLTEDataVPN, "\uE888"},
            {Icons.StatusVPN, "\uE889"},
            {Icons.WifiHotspot, "\uE88A"},
            {Icons.LanguageKor, "\uE88B"},
            {Icons.LanguageCht, "\uE88C"},
            {Icons.LanguageChs, "\uE88D"},
            {Icons.USB, "\uE88E"},
            {Icons.InkingToolFill, "\uE88F"},
            {Icons.View, "\uE890"},
            {Icons.HighlightFill, "\uE891"},
            {Icons.Previous, "\uE892"},
            {Icons.Next, "\uE893"},
            {Icons.Clear, "\uE894"},
            {Icons.Sync, "\uE895"},
            {Icons.Download, "\uE896"},
            {Icons.Help, "\uE897"},
            {Icons.Upload, "\uE898"},
            {Icons.Emoji, "\uE899"},
            {Icons.TwoPage, "\uE89A"},
            {Icons.LeaveChat, "\uE89B"},
            {Icons.MailForward, "\uE89C"},
            {Icons.RotateCamera, "\uE89E"},
            {Icons.ClosePane, "\uE89F"},
            {Icons.OpenPane, "\uE8A0"},
            {Icons.PreviewLink, "\uE8A1"},
            {Icons.AttachCamera, "\uE8A2"},
            {Icons.ZoomIn, "\uE8A3"},
            {Icons.Bookmarks, "\uE8A4"},
            {Icons.Document, "\uE8A5"},
            {Icons.ProtectedDocument, "\uE8A6"},
            {Icons.OpenInNewWindow, "\uE8A7"},
            {Icons.MailFill, "\uE8A8"},
            {Icons.ViewAll, "\uE8A9"},
            {Icons.VideoChat, "\uE8AA"},
            {Icons.Switch, "\uE8AB"},
            {Icons.Rename, "\uE8AC"},
            {Icons.Go, "\uE8AD"},
            {Icons.SurfaceHub, "\uE8AE"},
            {Icons.Remote, "\uE8AF"},
            {Icons.Click, "\uE8B0"},
            {Icons.Shuffle, "\uE8B1"},
            {Icons.Movies, "\uE8B2"},
            {Icons.SelectAll, "\uE8B3"},
            {Icons.Orientation, "\uE8B4"},
            {Icons.Import, "\uE8B5"},
            {Icons.ImportAll, "\uE8B6"},
            {Icons.Folder, "\uE8B7"},
            {Icons.Webcam, "\uE8B8"},
            {Icons.Picture, "\uE8B9"},
            {Icons.Caption, "\uE8BA"},
            {Icons.ChromeClose, "\uE8BB"},
            {Icons.ShowResults, "\uE8BC"},
            {Icons.Message, "\uE8BD"},
            {Icons.Leaf, "\uE8BE"},
            {Icons.CalendarDay, "\uE8BF"},
            {Icons.CalendarWeek, "\uE8C0"},
            {Icons.Characters, "\uE8C1"},
            {Icons.MailReplyAll, "\uE8C2"},
            {Icons.Read, "\uE8C3"},
            {Icons.ShowBcc, "\uE8C4"},
            {Icons.HideBcc, "\uE8C5"},
            {Icons.Cut, "\uE8C6"},
            {Icons.Copy, "\uE8C8"},
            {Icons.Important, "\uE8C9"},
            {Icons.MailReply, "\uE8CA"},
            {Icons.Sort, "\uE8CB"},
            {Icons.MobileTablet, "\uE8CC"},
            {Icons.DisconnectDrive, "\uE8CD"},
            {Icons.MapDrive, "\uE8CE"},
            {Icons.ContactPresence, "\uE8CF"},
            {Icons.Priority, "\uE8D0"},
            {Icons.GotoToday, "\uE8D1"},
            {Icons.Font, "\uE8D2"},
            {Icons.FontColor, "\uE8D3"},
            {Icons.Contact2, "\uE8D4"},
            {Icons.FolderFill, "\uE8D5"},
            {Icons.Audio, "\uE8D6"},
            {Icons.Permissions, "\uE8D7"},
            {Icons.DisableUpdates, "\uE8D8"},
            {Icons.Unfavorite, "\uE8D9"},
            {Icons.OpenLocal, "\uE8DA"},
            {Icons.Italic, "\uE8DB"},
            {Icons.Underline, "\uE8DC"},
            {Icons.Bold, "\uE8DD"},
            {Icons.MoveToFolder, "\uE8DE"},
            {Icons.LikeDislike, "\uE8DF"},
            {Icons.Dislike, "\uE8E0"},
            {Icons.Like, "\uE8E1"},
            {Icons.AlignRight, "\uE8E2"},
            {Icons.AlignCenter, "\uE8E3"},
            {Icons.AlignLeft, "\uE8E4"},
            {Icons.OpenFile, "\uE8E5"},
            {Icons.ClearSelection, "\uE8E6"},
            {Icons.FontDecrease, "\uE8E7"},
            {Icons.FontIncrease, "\uE8E8"},
            {Icons.FontSize, "\uE8E9"},
            {Icons.CellPhone, "\uE8EA"},
            {Icons.Reshare, "\uE8EB"},
            {Icons.Tag, "\uE8EC"},
            {Icons.RepeatOne, "\uE8ED"},
            {Icons.RepeatAll, "\uE8EE"},
            {Icons.Calculator, "\uE8EF"},
            {Icons.Directions, "\uE8F0"},
            {Icons.Library, "\uE8F1"},
            {Icons.ChatBubbles, "\uE8F2"},
            {Icons.PostUpdate, "\uE8F3"},
            {Icons.NewFolder, "\uE8F4"},
            {Icons.CalendarReply, "\uE8F5"},
            {Icons.UnsyncFolder, "\uE8F6"},
            {Icons.SyncFolder, "\uE8F7"},
            {Icons.BlockContact, "\uE8F8"},
            {Icons.SwitchApps, "\uE8F9"},
            {Icons.AddFriend, "\uE8FA"},
            {Icons.Accept, "\uE8FB"},
            {Icons.GoToStart, "\uE8FC"},
            {Icons.BulletedList, "\uE8FD"},
            {Icons.Scan, "\uE8FE"},
            {Icons.Preview, "\uE8FF"},
            {Icons.ZeroBars, "\uE904"},
            {Icons.OneBar, "\uE905"},
            {Icons.TwoBars, "\uE906"},
            {Icons.ThreeBars, "\uE907"},
            {Icons.FourBars, "\uE908"},
            {Icons.World, "\uE909"},
            {Icons.Comment, "\uE90A"},
            {Icons.MusicInfo, "\uE90B"},
            {Icons.DockLeft, "\uE90C"},
            {Icons.DockRight, "\uE90D"},
            {Icons.DockBottom, "\uE90E"},
            {Icons.Repair, "\uE90F"},
            {Icons.Accounts, "\uE910"},
            {Icons.DullSound, "\uE911"},
            {Icons.Manage, "\uE912"},
            {Icons.Street, "\uE913"},
            {Icons.Printer3D, "\uE914"},
            {Icons.RadioBullet, "\uE915"},
            {Icons.Stopwatch, "\uE916"},
            {Icons.Photo, "\uE91B"},
            {Icons.ActionCenter, "\uE91C"},
            {Icons.FullCircleMask, "\uE91F"},
            {Icons.ChromeMinimize, "\uE921"},
            {Icons.ChromeMaximize, "\uE922"},
            {Icons.ChromeRestore, "\uE923"},
            {Icons.Annotation, "\uE924"},
            {Icons.BackSpaceQWERTYSm, "\uE925"},
            {Icons.BackSpaceQWERTYMd, "\uE926"},
            {Icons.Swipe, "\uE927"},
            {Icons.Fingerprint, "\uE928"},
            {Icons.Handwriting, "\uE929"},
            {Icons.ChromeBackToWindow, "\uE92C"},
            {Icons.ChromeFullScreen, "\uE92D"},
            {Icons.KeyboardStandard, "\uE92E"},
            {Icons.KeyboardDismiss, "\uE92F"},
            {Icons.Completed, "\uE930"},
            {Icons.ChromeAnnotate, "\uE931"},
            {Icons.Label, "\uE932"},
            {Icons.IBeam, "\uE933"},
            {Icons.IBeamOutline, "\uE934"},
            {Icons.FlickDown, "\uE935"},
            {Icons.FlickUp, "\uE936"},
            {Icons.FlickLeft, "\uE937"},
            {Icons.FlickRight, "\uE938"},
            {Icons.FeedbackApp, "\uE939"},
            {Icons.MusicAlbum, "\uE93C"},
            {Icons.Streaming, "\uE93E"},
            {Icons.Code, "\uE943"},
            {Icons.ReturnToWindow, "\uE944"},
            {Icons.LightningBolt, "\uE945"},
            {Icons.Info, "\uE946"},
            {Icons.CalculatorMultiply, "\uE947"},
            {Icons.CalculatorAddition, "\uE948"},
            {Icons.CalculatorSubtract, "\uE949"},
            {Icons.CalculatorDivide, "\uE94A"},
            {Icons.CalculatorSquareroot, "\uE94B"},
            {Icons.CalculatorPercentage, "\uE94C"},
            {Icons.CalculatorNegate, "\uE94D"},
            {Icons.CalculatorEqualTo, "\uE94E"},
            {Icons.CalculatorBackspace, "\uE94F"},
            {Icons.Component, "\uE950"},
            {Icons.DMC, "\uE951"},
            {Icons.Dock, "\uE952"},
            {Icons.MultimediaDMS, "\uE953"},
            {Icons.MultimediaDVR, "\uE954"},
            {Icons.MultimediaPMP, "\uE955"},
            {Icons.PrintfaxPrinterFile, "\uE956"},
            {Icons.Sensor, "\uE957"},
            {Icons.StorageOptical, "\uE958"},
            {Icons.Communications, "\uE95A"},
            {Icons.Headset, "\uE95B"},
            {Icons.Projector, "\uE95D"},
            {Icons.Health, "\uE95E"},
            {Icons.Webcam2, "\uE960"},
            {Icons.Input, "\uE961"},
            {Icons.Mouse, "\uE962"},
            {Icons.Smartcard, "\uE963"},
            {Icons.SmartcardVirtual, "\uE964"},
            {Icons.MediaStorageTower, "\uE965"},
            {Icons.ReturnKeySm, "\uE966"},
            {Icons.GameConsole, "\uE967"},
            {Icons.Network, "\uE968"},
            {Icons.StorageNetworkWireless, "\uE969"},
            {Icons.StorageTape, "\uE96A"},
            {Icons.ChevronUpSmall, "\uE96D"},
            {Icons.ChevronDownSmall, "\uE96E"},
            {Icons.ChevronLeftSmall, "\uE96F"},
            {Icons.ChevronRightSmall, "\uE970"},
            {Icons.ChevronUpMed, "\uE971"},
            {Icons.ChevronDownMed, "\uE972"},
            {Icons.ChevronLeftMed, "\uE973"},
            {Icons.ChevronRightMed, "\uE974"},
            {Icons.Devices2, "\uE975"},
            {Icons.ExpandTile, "\uE976"},
            {Icons.PC1, "\uE977"},
            {Icons.PresenceChicklet, "\uE978"},
            {Icons.PresenceChickletVideo, "\uE979"},
            {Icons.Reply, "\uE97A"},
            {Icons.SetTile, "\uE97B"},
            {Icons.Type, "\uE97C"},
            {Icons.Korean, "\uE97D"},
            {Icons.HalfAlpha, "\uE97E"},
            {Icons.FullAlpha, "\uE97F"},
            {Icons.Key12On, "\uE980"},
            {Icons.ChineseChangjie, "\uE981"},
            {Icons.QWERTYOn, "\uE982"},
            {Icons.QWERTYOff, "\uE983"},
            {Icons.ChineseQuick, "\uE984"},
            {Icons.Japanese, "\uE985"},
            {Icons.FullHiragana, "\uE986"},
            {Icons.FullKatakana, "\uE987"},
            {Icons.HalfKatakana, "\uE988"},
            {Icons.ChineseBoPoMoFo, "\uE989"},
            {Icons.ChinesePinyin, "\uE98A"},
            {Icons.ConstructionCone, "\uE98F"},
            {Icons.XboxOneConsole, "\uE990"},
            {Icons.Volume0, "\uE992"},
            {Icons.Volume1, "\uE993"},
            {Icons.Volume2, "\uE994"},
            {Icons.Volume3, "\uE995"},
            {Icons.BatteryUnknown, "\uE996"},
            {Icons.WifiAttentionOverlay, "\uE998"},
            {Icons.Robot, "\uE99A"},
            {Icons.TapAndSend, "\uE9A1"},
            {Icons.PasswordKeyShow, "\uE9A8"},
            {Icons.PasswordKeyHide, "\uE9A9"},
            {Icons.BidiLtr, "\uE9AA"},
            {Icons.BidiRtl, "\uE9AB"},
            {Icons.ForwardSm, "\uE9AC"},
            {Icons.CommaKey, "\uE9AD"},
            {Icons.DashKey, "\uE9AE"},
            {Icons.DullSoundKey, "\uE9AF"},
            {Icons.HalfDullSound, "\uE9B0"},
            {Icons.RightDoubleQuote, "\uE9B1"},
            {Icons.LeftDoubleQuote, "\uE9B2"},
            {Icons.PuncKeyRightBottom, "\uE9B3"},
            {Icons.PuncKey1, "\uE9B4"},
            {Icons.PuncKey2, "\uE9B5"},
            {Icons.PuncKey3, "\uE9B6"},
            {Icons.PuncKey4, "\uE9B7"},
            {Icons.PuncKey5, "\uE9B8"},
            {Icons.PuncKey6, "\uE9B9"},
            {Icons.PuncKey9, "\uE9BA"},
            {Icons.PuncKey7, "\uE9BB"},
            {Icons.PuncKey8, "\uE9BC"},
            {Icons.Frigid, "\uE9CA"},
            {Icons.Diagnostic, "\uE9D9"},
            {Icons.Process, "\uE9F3"},
            {Icons.DisconnectDisplay, "\uEA14"},
            {Icons.Info2, "\uEA1F"},
            {Icons.ActionCenterAsterisk, "\uEA21"},
            {Icons.Beta, "\uEA24"},
            {Icons.SaveCopy, "\uEA35"},
            {Icons.List, "\uEA37"},
            {Icons.Asterisk, "\uEA38"},
            {Icons.ErrorBadge, "\uEA39"},
            {Icons.CircleRing, "\uEA3A"},
            {Icons.CircleFill, "\uEA3B"},
            {Icons.AllAppsMirrored, "\uEA40"},
            {Icons.BookmarksMirrored, "\uEA41"},
            {Icons.BulletedListMirrored, "\uEA42"},
            {Icons.CallForwardInternationalMirrored, "\uEA43"},
            {Icons.CallForwardRoamingMirrored, "\uEA44"},
            {Icons.ChromeBackMirrored, "\uEA47"},
            {Icons.ClearSelectionMirrored, "\uEA48"},
            {Icons.ClosePaneMirrored, "\uEA49"},
            {Icons.ContactInfoMirrored, "\uEA4A"},
            {Icons.DockRightMirrored, "\uEA4B"},
            {Icons.DockLeftMirrored, "\uEA4C"},
            {Icons.ExpandTileMirrored, "\uEA4E"},
            {Icons.GoMirrored, "\uEA4F"},
            {Icons.GripperResizeMirrored, "\uEA50"},
            {Icons.HelpMirrored, "\uEA51"},
            {Icons.ImportMirrored, "\uEA52"},
            {Icons.ImportAllMirrored, "\uEA53"},
            {Icons.LeaveChatMirrored, "\uEA54"},
            {Icons.ListMirrored, "\uEA55"},
            {Icons.MailForwardMirrored, "\uEA56"},
            {Icons.MailReplyMirrored, "\uEA57"},
            {Icons.MailReplyAllMirrored, "\uEA58"},
            {Icons.OpenPaneMirrored, "\uEA5B"},
            {Icons.OpenWithMirrored, "\uEA5C"},
            {Icons.ParkingLocationMirrored, "\uEA5E"},
            {Icons.ResizeMouseMediumMirrored, "\uEA5F"},
            {Icons.ResizeMouseSmallMirrored, "\uEA60"},
            {Icons.ResizeMouseTallMirrored, "\uEA61"},
            {Icons.ResizeTouchNarrowerMirrored, "\uEA62"},
            {Icons.SendMirrored, "\uEA63"},
            {Icons.SendFillMirrored, "\uEA64"},
            {Icons.ShowResultsMirrored, "\uEA65"},
            {Icons.Media, "\uEA69"},
            {Icons.SyncError, "\uEA6A"},
            {Icons.Devices3, "\uEA6C"},
            {Icons.Lightbulb, "\uEA80"},
            {Icons.StatusCircle, "\uEA81"},
            {Icons.StatusTriangle, "\uEA82"},
            {Icons.StatusError, "\uEA83"},
            {Icons.StatusWarning, "\uEA84"},
            {Icons.Puzzle, "\uEA86"},
            {Icons.CalendarSolid, "\uEA89"},
            {Icons.HomeSolid, "\uEA8A"},
            {Icons.ParkingLocationSolid, "\uEA8B"},
            {Icons.ContactSolid, "\uEA8C"},
            {Icons.ConstructionSolid, "\uEA8D"},
            {Icons.AccidentSolid, "\uEA8E"},
            {Icons.Ringer, "\uEA8F"},
            {Icons.ThoughtBubble, "\uEA91"},
            {Icons.HeartBroken, "\uEA92"},
            {Icons.BatteryCharging10, "\uEA93"},
            {Icons.BatterySaver9, "\uEA94"},
            {Icons.BatterySaver10, "\uEA95"},
            {Icons.CallForwardingMirrored, "\uEA97"},
            {Icons.MultiSelectMirrored, "\uEA98"},
            {Icons.Broom, "\uEA99"},
            {Icons.Trackers, "\uEADF"},
            {Icons.PieSingle, "\uEB05"},
            {Icons.StockDown, "\uEB0F"},
            {Icons.StockUp, "\uEB11"},
            {Icons.Drop, "\uEB42"},
            {Icons.BusSolid, "\uEB47"},
            {Icons.FerrySolid, "\uEB48"},
            {Icons.StartPointSolid, "\uEB49"},
            {Icons.StopPointSolid, "\uEB4A"},
            {Icons.EndPointSolid, "\uEB4B"},
            {Icons.AirplaneSolid, "\uEB4C"},
            {Icons.TrainSolid, "\uEB4D"},
            {Icons.WorkSolid, "\uEB4E"},
            {Icons.ReminderFill, "\uEB4F"},
            {Icons.Reminder, "\uEB50"},
            {Icons.Heart, "\uEB51"},
            {Icons.HeartFill, "\uEB52"},
            {Icons.EthernetError, "\uEB55"},
            {Icons.EthernetWarning, "\uEB56"},
            {Icons.StatusConnecting1, "\uEB57"},
            {Icons.StatusConnecting2, "\uEB58"},
            {Icons.StatusUnsecure, "\uEB59"},
            {Icons.WifiError0, "\uEB5A"},
            {Icons.WifiError1, "\uEB5B"},
            {Icons.WifiError2, "\uEB5C"},
            {Icons.WifiError3, "\uEB5D"},
            {Icons.WifiError4, "\uEB5E"},
            {Icons.WifiWarning0, "\uEB5F"},
            {Icons.WifiWarning1, "\uEB60"},
            {Icons.WifiWarning2, "\uEB61"},
            {Icons.WifiWarning3, "\uEB62"},
            {Icons.WifiWarning4, "\uEB63"},
            {Icons.Devices4, "\uEB66"},
            {Icons.NUIIris, "\uEB67"},
            {Icons.NUIFace, "\uEB68"},
            {Icons.EditMirrored, "\uEB7E"},
            {Icons.NUIFPStartSlideHand, "\uEB82"},
            {Icons.NUIFPStartSlideAction, "\uEB83"},
            {Icons.NUIFPContinueSlideHand, "\uEB84"},
            {Icons.NUIFPContinueSlideAction, "\uEB85"},
            {Icons.NUIFPRollRightHand, "\uEB86"},
            {Icons.NUIFPRollRightHandAction, "\uEB87"},
            {Icons.NUIFPRollLeftHand, "\uEB88"},
            {Icons.NUIFPRollLeftAction, "\uEB89"},
            {Icons.NUIFPPressHand, "\uEB8A"},
            {Icons.NUIFPPressAction, "\uEB8B"},
            {Icons.NUIFPPressRepeatHand, "\uEB8C"},
            {Icons.NUIFPPressRepeatAction, "\uEB8D"},
            {Icons.StatusErrorFull, "\uEB90"},
            {Icons.MultitaskExpanded, "\uEB91"},
            {Icons.Certificate, "\uEB95"},
            {Icons.BackSpaceQWERTYLg, "\uEB96"},
            {Icons.ReturnKeyLg, "\uEB97"},
            {Icons.FastForward, "\uEB9D"},
            {Icons.Rewind, "\uEB9E"},
            {Icons.Photo2, "\uEB9F"},
            {Icons.MobBattery0, "\uEBA0"},
            {Icons.MobBattery1, "\uEBA1"},
            {Icons.MobBattery2, "\uEBA2"},
            {Icons.MobBattery3, "\uEBA3"},
            {Icons.MobBattery4, "\uEBA4"},
            {Icons.MobBattery5, "\uEBA5"},
            {Icons.MobBattery6, "\uEBA6"},
            {Icons.MobBattery7, "\uEBA7"},
            {Icons.MobBattery8, "\uEBA8"},
            {Icons.MobBattery9, "\uEBA9"},
            {Icons.MobBattery10, "\uEBAA"},
            {Icons.MobBatteryCharging0, "\uEBAB"},
            {Icons.MobBatteryCharging1, "\uEBAC"},
            {Icons.MobBatteryCharging2, "\uEBAD"},
            {Icons.MobBatteryCharging3, "\uEBAE"},
            {Icons.MobBatteryCharging4, "\uEBAF"},
            {Icons.MobBatteryCharging5, "\uEBB0"},
            {Icons.MobBatteryCharging6, "\uEBB1"},
            {Icons.MobBatteryCharging7, "\uEBB2"},
            {Icons.MobBatteryCharging8, "\uEBB3"},
            {Icons.MobBatteryCharging9, "\uEBB4"},
            {Icons.MobBatteryCharging10, "\uEBB5"},
            {Icons.MobBatterySaver0, "\uEBB6"},
            {Icons.MobBatterySaver1, "\uEBB7"},
            {Icons.MobBatterySaver2, "\uEBB8"},
            {Icons.MobBatterySaver3, "\uEBB9"},
            {Icons.MobBatterySaver4, "\uEBBA"},
            {Icons.MobBatterySaver5, "\uEBBB"},
            {Icons.MobBatterySaver6, "\uEBBC"},
            {Icons.MobBatterySaver7, "\uEBBD"},
            {Icons.MobBatterySaver8, "\uEBBE"},
            {Icons.MobBatterySaver9, "\uEBBF"},
            {Icons.MobBatterySaver10, "\uEBC0"},
            {Icons.DictionaryCloud, "\uEBC3"},
            {Icons.ResetDrive, "\uEBC4"},
            {Icons.VolumeBars, "\uEBC5"},
            {Icons.Project, "\uEBC6"},
            {Icons.AdjustHologram, "\uEBD2"},
            {Icons.WifiCallBars, "\uEBD4"},
            {Icons.WifiCall0, "\uEBD5"},
            {Icons.WifiCall1, "\uEBD6"},
            {Icons.WifiCall2, "\uEBD7"},
            {Icons.WifiCall3, "\uEBD8"},
            {Icons.WifiCall4, "\uEBD9"},
            {Icons.DeviceDiscovery, "\uEBDE"},
            {Icons.WindDirection, "\uEBE6"},
            {Icons.RightArrowKeyTime0, "\uEBE7"},
            {Icons.TabletMode, "\uEBFC"},
            {Icons.StatusCircleLeft, "\uEBFD"},
            {Icons.StatusTriangleLeft, "\uEBFE"},
            {Icons.StatusErrorLeft, "\uEBFF"},
            {Icons.StatusWarningLeft, "\uEC00"},
            {Icons.MobBatteryUnknown, "\uEC02"},
            {Icons.NetworkTower, "\uEC05"},
            {Icons.CityNext, "\uEC06"},
            {Icons.CityNext2, "\uEC07"},
            {Icons.Courthouse, "\uEC08"},
            {Icons.Groceries, "\uEC09"},
            {Icons.Sustainable, "\uEC0A"},
            {Icons.BuildingEnergy, "\uEC0B"},
            {Icons.ToggleFilled, "\uEC11"},
            {Icons.ToggleBorder, "\uEC12"},
            {Icons.SliderThumb, "\uEC13"},
            {Icons.ToggleThumb, "\uEC14"},
            {Icons.MiracastLogoSmall, "\uEC15"},
            {Icons.MiracastLogoLarge, "\uEC16"},
            {Icons.PLAP, "\uEC19"},
            {Icons.Badge, "\uEC1B"},
            {Icons.SignalRoaming, "\uEC1E"},
            {Icons.MobileLocked, "\uEC20"},
            {Icons.InsiderHubApp, "\uEC24"},
            {Icons.PersonalFolder, "\uEC25"},
            {Icons.HomeGroup, "\uEC26"},
            {Icons.MyNetwork, "\uEC27"},
            {Icons.KeyboardFull, "\uEC31"},
            {Icons.MobSignal1, "\uEC37"},
            {Icons.MobSignal2, "\uEC38"},
            {Icons.MobSignal3, "\uEC39"},
            {Icons.MobSignal4, "\uEC3A"},
            {Icons.MobSignal5, "\uEC3B"},
            {Icons.MobWifi1, "\uEC3C"},
            {Icons.MobWifi2, "\uEC3D"},
            {Icons.MobWifi3, "\uEC3E"},
            {Icons.MobWifi4, "\uEC3F"},
            {Icons.MobAirplane, "\uEC40"},
            {Icons.MobBluetooth, "\uEC41"},
            {Icons.MobActionCenter, "\uEC42"},
            {Icons.MobLocation, "\uEC43"},
            {Icons.MobWifiHotspot, "\uEC44"},
            {Icons.LanguageJpn, "\uEC45"},
            {Icons.MobQuietHours, "\uEC46"},
            {Icons.MobDrivingMode, "\uEC47"},
            {Icons.SpeedOff, "\uEC48"},
            {Icons.SpeedMedium, "\uEC49"},
            {Icons.SpeedHigh, "\uEC4A"},
            {Icons.ThisPC, "\uEC4E"},
            {Icons.MusicNote, "\uEC4F"},
            {Icons.FileExplorer, "\uEC50"},
            {Icons.FileExplorerApp, "\uEC51"},
            {Icons.LeftArrowKeyTime0, "\uEC52"},
            {Icons.MicOff, "\uEC54"},
            {Icons.MicSleep, "\uEC55"},
            {Icons.MicError, "\uEC56"},
            {Icons.PlaybackRate1x, "\uEC57"},
            {Icons.PlaybackRateOther, "\uEC58"},
            {Icons.CashDrawer, "\uEC59"},
            {Icons.BarcodeScanner, "\uEC5A"},
            {Icons.ReceiptPrinter, "\uEC5B"},
            {Icons.MagStripeReader, "\uEC5C"},
            {Icons.CompletedSolid, "\uEC61"},
            {Icons.CompanionApp, "\uEC64"},
            {Icons.SwipeRevealArt, "\uEC6D"},
            {Icons.MicOn, "\uEC71"},
            {Icons.MicClipping, "\uEC72"},
            {Icons.TabletSelected, "\uEC74"},
            {Icons.MobileSelected, "\uEC75"},
            {Icons.LaptopSelected, "\uEC76"},
            {Icons.TVMonitorSelected, "\uEC77"},
            {Icons.DeveloperTools, "\uEC7A"},
            {Icons.MobCallForwarding, "\uEC7E"},
            {Icons.MobCallForwardingMirrored, "\uEC7F"},
            {Icons.BodyCam, "\uEC80"},
            {Icons.PoliceCar, "\uEC81"},
            {Icons.Draw, "\uEC87"},
            {Icons.DrawSolid, "\uEC88"},
            {Icons.LowerBrightness, "\uEC8A"},
            {Icons.ScrollUpDown, "\uEC8F"},
            {Icons.DateTime, "\uEC92"},
            {Icons.Tiles, "\uECA5"},
            {Icons.PartyLeader, "\uECA7"},
            {Icons.AppIconDefault, "\uECAA"},
            {Icons.AddSurfaceHub, "\uECC4"},
            {Icons.DevUpdate, "\uECC5"},
            {Icons.Unit, "\uECC6"},
            {Icons.AddTo, "\uECC8"},
            {Icons.RemoveFrom, "\uECC9"},
            {Icons.RadioBtnOff, "\uECCA"},
            {Icons.RadioBtnOn, "\uECCB"},
            {Icons.RadioBullet2, "\uECCC"},
            {Icons.ExploreContent, "\uECCD"},
            {Icons.ScrollMode, "\uECE7"},
            {Icons.ZoomMode, "\uECE8"},
            {Icons.PanMode, "\uECE9"},
            {Icons.WiredUSB, "\uECF0"},
            {Icons.WirelessUSB, "\uECF1"},
            {Icons.USBSafeConnect, "\uECF3"},
            {Icons.ActionCenterNotificationMirrored, "\uED0C"},
            {Icons.ActionCenterMirrored, "\uED0D"},
            {Icons.ResetDevice, "\uED10"},
            {Icons.Feedback, "\uED15"},
            {Icons.Subtitles, "\uED1E"},
            {Icons.SubtitlesAudio, "\uED1F"},
            {Icons.CalendarMirrored, "\uED28"},
            {Icons.eSIM, "\uED2A"},
            {Icons.eSIMNoProfile, "\uED2B"},
            {Icons.eSIMLocked, "\uED2C"},
            {Icons.eSIMBusy, "\uED2D"},
            {Icons.SignalError, "\uED2E"},
            {Icons.StreamingEnterprise, "\uED2F"},
            {Icons.Headphone0, "\uED30"},
            {Icons.Headphone1, "\uED31"},
            {Icons.Headphone2, "\uED32"},
            {Icons.Headphone3, "\uED33"},
            {Icons.KeyboardBrightness, "\uED39"},
            {Icons.KeyboardLowerBrightness, "\uED3A"},
            {Icons.SkipBack10, "\uED3C"},
            {Icons.SkipForward30, "\uED3D"},
            {Icons.TreeFolderFolder, "\uED41"},
            {Icons.TreeFolderFolderFill, "\uED42"},
            {Icons.TreeFolderFolderOpen, "\uED43"},
            {Icons.TreeFolderFolderOpenFill, "\uED44"},
            {Icons.MultimediaDMP, "\uED47"},
            {Icons.KeyboardOneHanded, "\uED4C"},
            {Icons.Narrator, "\uED4D"},
            {Icons.EmojiTabPeople, "\uED53"},
            {Icons.EmojiTabSmilesAnimals, "\uED54"},
            {Icons.EmojiTabCelebrationObjects, "\uED55"},
            {Icons.EmojiTabFoodPlants, "\uED56"},
            {Icons.EmojiTabTransitPlaces, "\uED57"},
            {Icons.EmojiTabSymbols, "\uED58"},
            {Icons.EmojiTabTextSmiles, "\uED59"},
            {Icons.EmojiTabFavorites, "\uED5A"},
            {Icons.EmojiSwatch, "\uED5B"},
            {Icons.ConnectApp, "\uED5C"},
            {Icons.CompanionDeviceFramework, "\uED5D"},
            {Icons.Ruler, "\uED5E"},
            {Icons.FingerInking, "\uED5F"},
            {Icons.StrokeErase, "\uED60"},
            {Icons.PointErase, "\uED61"},
            {Icons.ClearAllInk, "\uED62"},
            {Icons.Pencil, "\uED63"},
            {Icons.Marker, "\uED64"},
            {Icons.InkingCaret, "\uED65"},
            {Icons.InkingColorOutline, "\uED66"},
            {Icons.InkingColorFill, "\uED67"},
            {Icons.HardDrive, "\uEDA2"},
            {Icons.NetworkAdapter, "\uEDA3"},
            {Icons.Touchscreen, "\uEDA4"},
            {Icons.NetworkPrinter, "\uEDA5"},
            {Icons.CloudPrinter, "\uEDA6"},
            {Icons.KeyboardShortcut, "\uEDA7"},
            {Icons.BrushSize, "\uEDA8"},
            {Icons.NarratorForward, "\uEDA9"},
            {Icons.NarratorForwardMirrored, "\uEDAA"},
            {Icons.SyncBadge12, "\uEDAB"},
            {Icons.RingerBadge12, "\uEDAC"},
            {Icons.AsteriskBadge12, "\uEDAD"},
            {Icons.ErrorBadge12, "\uEDAE"},
            {Icons.CircleRingBadge12, "\uEDAF"},
            {Icons.CircleFillBadge12, "\uEDB0"},
            {Icons.ImportantBadge12, "\uEDB1"},
            {Icons.MailBadge12, "\uEDB3"},
            {Icons.PauseBadge12, "\uEDB4"},
            {Icons.PlayBadge12, "\uEDB5"},
            {Icons.PenWorkspace, "\uEDC6"},
            {Icons.Export, "\uEDE1"},
            {Icons.ExportMirrored, "\uEDE2"},
            {Icons.CaligraphyPen, "\uEDFB"},
            {Icons.ReplyMirrored, "\uEE35"},
            {Icons.LockscreenDesktop, "\uEE3F"},
            {Icons.Multitask16, "\uEE40"},
            {Icons.Play36, "\uEE4A"},
            {Icons.PenPalette, "\uEE56"},
            {Icons.GuestUser, "\uEE57"},
            {Icons.SettingsBattery, "\uEE63"},
            {Icons.TaskbarPhone, "\uEE64"},
            {Icons.LockScreenGlance, "\uEE65"},
            {Icons.ImageExport, "\uEE71"},
            {Icons.WifiEthernet, "\uEE77"},
            {Icons.ActionCenterQuiet, "\uEE79"},
            {Icons.ActionCenterQuietNotification, "\uEE7A"},
            {Icons.TrackersMirrored, "\uEE92"},
            {Icons.DateTimeMirrored, "\uEE93"},
            {Icons.Wheel, "\uEE94"},
            {Icons.PenWorkspaceMirrored, "\uEF15"},
            {Icons.PenPaletteMirrored, "\uEF16"},
            {Icons.StrokeEraseMirrored, "\uEF17"},
            {Icons.PointEraseMirrored, "\uEF18"},
            {Icons.ClearAllInkMirrored, "\uEF19"},
            {Icons.BackgroundToggle, "\uEF1F"},
            {Icons.Marquee, "\uEF20"},
            {Icons.Relationship, "\uF003"},
            {Icons.DefaultAPN, "\uF080"},
            {Icons.UserAPN, "\uF081"},
            {Icons.DoublePinyin, "\uF085"},
            {Icons.BlueLight, "\uF08C"},
            {Icons.ButtonA, "\uF093"},
            {Icons.ButtonB, "\uF094"},
            {Icons.ButtonY, "\uF095"},
            {Icons.ButtonX, "\uF096"},
            {Icons.ArrowUp8, "\uF0AD"},
            {Icons.ArrowDown8, "\uF0AE"},
            {Icons.ArrowRight8, "\uF0AF"},
            {Icons.ArrowLeft8, "\uF0B0"},
            {Icons.QuarentinedItems, "\uF0B2"},
            {Icons.QuarentinedItemsMirrored, "\uF0B3"},
            {Icons.Protractor, "\uF0B4"},
            {Icons.ChecklistMirrored, "\uF0B5"},
            {Icons.StatusCircle7, "\uF0B6"},
            {Icons.StatusCheckmark7, "\uF0B7"},
            {Icons.StatusErrorCircle7, "\uF0B8"},
            {Icons.Connected, "\uF0B9"},
            {Icons.PencilFill, "\uF0C6"},
            {Icons.CalligraphyFill, "\uF0C7"},
            {Icons.QuarterStarLeft, "\uF0CA"},
            {Icons.QuarterStarRight, "\uF0CB"},
            {Icons.ThreeQuarterStarLeft, "\uF0CC"},
            {Icons.ThreeQuarterStarRight, "\uF0CD"},
            {Icons.QuietHoursBadge12, "\uF0CE"},
            {Icons.BackMirrored, "\uF0D2"},
            {Icons.ForwardMirrored, "\uF0D3"},
            {Icons.ChromeBackContrast, "\uF0D5"},
            {Icons.ChromeBackContrastMirrored, "\uF0D6"},
            {Icons.ChromeBackToWindowContrast, "\uF0D7"},
            {Icons.ChromeFullScreenContrast, "\uF0D8"},
            {Icons.GridView, "\uF0E2"},
            {Icons.ClipboardList, "\uF0E3"},
            {Icons.ClipboardListMirrored, "\uF0E4"},
            {Icons.OutlineQuarterStarLeft, "\uF0E5"},
            {Icons.OutlineQuarterStarRight, "\uF0E6"},
            {Icons.OutlineHalfStarLeft, "\uF0E7"},
            {Icons.OutlineHalfStarRight, "\uF0E8"},
            {Icons.OutlineThreeQuarterStarLeft, "\uF0E9"},
            {Icons.OutlineThreeQuarterStarRight, "\uF0EA"},
            {Icons.SpatialVolume0, "\uF0EB"},
            {Icons.SpatialVolume1, "\uF0EC"},
            {Icons.SpatialVolume2, "\uF0ED"},
            {Icons.SpatialVolume3, "\uF0EE"},
            {Icons.OutlineStarLeftHalf, "\uF0F7"},
            {Icons.OutlineStarRightHalf, "\uF0F8"},
            {Icons.ChromeAnnotateContrast, "\uF0F9"},
            {Icons.DefenderBadge12, "\uF0FB"},
            {Icons.DetachablePC, "\uF103"},
            {Icons.LeftStick, "\uF108"},
            {Icons.RightStick, "\uF109"},
            {Icons.TriggerLeft, "\uF10A"},
            {Icons.TriggerRight, "\uF10B"},
            {Icons.BumperLeft, "\uF10C"},
            {Icons.BumperRight, "\uF10D"},
            {Icons.Dpad, "\uF10E"},
            {Icons.EnglishPunctuation, "\uF110"},
            {Icons.ChinesePunctuation, "\uF111"},
            {Icons.HMD, "\uF119"},
            {Icons.PaginationDotOutline10, "\uF126"},
            {Icons.PaginationDotSolid10, "\uF127"},
            {Icons.StrokeErase2, "\uF128"},
            {Icons.SmallErase, "\uF129"},
            {Icons.LargeErase, "\uF12A"},
            {Icons.FolderHorizontal, "\uF12B"},
            {Icons.MicrophoneListening, "\uF12E"},
            {Icons.StatusExclamationCircle7, "\uF12F"},
            {Icons.StatusCircleOuter, "\uF136"},
            {Icons.StatusCircleInner, "\uF137"},
            {Icons.StatusCircleRing, "\uF138"},
            {Icons.StatusTriangleOuter, "\uF139"},
            {Icons.StatusTriangleInner, "\uF13A"},
            {Icons.StatusTriangleExclamation, "\uF13B"},
            {Icons.StatusCircleExclamation, "\uF13C"},
            {Icons.StatusCircleErrorX, "\uF13D"},
            {Icons.StatusCircleCheckmark, "\uF13E"},
            {Icons.StatusCircleInfo, "\uF13F"},
            {Icons.StatusCircleBlock, "\uF140"},
            {Icons.StatusCircleBlock2, "\uF141"},
            {Icons.StatusCircleQuestionMark, "\uF142"},
            {Icons.StatusCircleSync, "\uF143"},
            {Icons.Dial1, "\uF146"},
            {Icons.Dial2, "\uF147"},
            {Icons.Dial3, "\uF148"},
            {Icons.Dial4, "\uF149"},
            {Icons.Dial5, "\uF14A"},
            {Icons.Dial6, "\uF14B"},
            {Icons.Dial7, "\uF14C"},
            {Icons.Dial8, "\uF14D"},
            {Icons.Dial9, "\uF14E"},
            {Icons.Dial10, "\uF14F"},
            {Icons.Dial11, "\uF150"},
            {Icons.Dial12, "\uF151"},
            {Icons.Dial13, "\uF152"},
            {Icons.Dial14, "\uF153"},
            {Icons.Dial15, "\uF154"},
            {Icons.Dial16, "\uF155"},
            {Icons.DialShape1, "\uF156"},
            {Icons.DialShape2, "\uF157"},
            {Icons.DialShape3, "\uF158"},
            {Icons.DialShape4, "\uF159"},
            {Icons.TollSolid, "\uF161"},
            {Icons.TrafficCongestionSolid, "\uF163"},
            {Icons.ExploreContentSingle, "\uF164"},
            {Icons.CollapseContent, "\uF165"},
            {Icons.CollapseContentSingle, "\uF166"},
            {Icons.InfoSolid, "\uF167"},
            {Icons.GroupList, "\uF168"},
            {Icons.CaretBottomRightSolidCenter8, "\uF169"},
            {Icons.ProgressRingDots, "\uF16A"},
            {Icons.Checkbox14, "\uF16B"},
            {Icons.CheckboxComposite14, "\uF16C"},
            {Icons.CheckboxIndeterminateCombo14, "\uF16D"},
            {Icons.CheckboxIndeterminateCombo, "\uF16E"},
            {Icons.StatusPause7, "\uF175"},
            {Icons.CharacterAppearance, "\uF17F"},
            {Icons.Lexicon, "\uF180"},
            {Icons.ScreenTime, "\uF182"},
            {Icons.HeadlessDevice, "\uF191"},
            {Icons.NetworkSharing, "\uF193"},
            {Icons.WindowsInsider, "\uF1AD"},
            {Icons.ChromeSwitch, "\uF1CB"},
            {Icons.ChromeSwitchContast, "\uF1CC"},
            {Icons.StatusCheckmark, "\uF1D8"},
            {Icons.StatusCheckmarkLeft, "\uF1D9"},
            {Icons.KeyboardLeftAligned, "\uF20C"},
            {Icons.KeyboardRightAligned, "\uF20D"},
            {Icons.KeyboardSettings, "\uF210"},
            {Icons.IOT, "\uF22C"},
            {Icons.ExploitProtectionSettings, "\uF259"},
            {Icons.KeyboardNarrow, "\uF260"},
            {Icons.Keyboard12Key, "\uF261"},
            {Icons.KeyboardDock, "\uF26B"},
            {Icons.KeyboardUndock, "\uF26C"},
            {Icons.KeyboardLeftDock, "\uF26D"},
            {Icons.KeyboardRightDock, "\uF26E"},
            {Icons.Ear, "\uF270"},
            {Icons.PointerHand, "\uF271"},
            {Icons.Bullseye, "\uF272"},
            {Icons.PassiveAuthentication, "\uF32A"},
            {Icons.NetworkOffline, "\uF384"},
            {Icons.NetworkConnected, "\uF385"},
            {Icons.NetworkConnectedCheckmark, "\uF386"}
        };
    }

    public enum Icons
    {
        GlobalNavigationButton,
        Wifi,
        Bluetooth,
        Connect,
        InternetSharing,
        VPN,
        Brightness,
        MapPin,
        QuietHours,
        Airplane,
        Tablet,
        QuickNote,
        RememberedDevice,
        ChevronDown,
        ChevronUp,
        Edit,
        Add,
        Cancel,
        More,
        Settings,
        Video,
        Mail,
        People,
        Phone,
        Pin,
        Shop,
        Stop,
        Link,
        Filter,
        AllApps,
        Zoom,
        ZoomOut,
        Microphone,
        Search,
        Camera,
        Attach,
        Send,
        SendFill,
        WalkSolid,
        InPrivate,
        FavoriteList,
        PageSolid,
        Forward,
        Back,
        Refresh,
        Share,
        Lock,
        ReportHacked,
        FavoriteStar,
        FavoriteStarFill,
        Remove,
        Checkbox,
        CheckboxComposite,
        CheckboxFill,
        CheckboxIndeterminate,
        CheckboxCompositeReversed,
        CheckMark,
        BackToWindow,
        FullScreen,
        ResizeTouchLarger,
        ResizeTouchSmaller,
        ResizeMouseSmall,
        ResizeMouseMedium,
        ResizeMouseWide,
        ResizeMouseTall,
        ResizeMouseLarge,
        SwitchUser,
        Print,
        Up,
        Down,
        OEM,
        Delete,
        Save,
        Mute,
        BackSpaceQWERTY,
        ReturnKey,
        UpArrowShiftKey,
        Cloud,
        Flashlight,
        RotationLock,
        CommandPrompt,
        SIPMove,
        SIPUndock,
        SIPRedock,
        EraseTool,
        UnderscoreSpace,
        GripperTool,
        Dialpad,
        PageLeft,
        PageRight,
        MultiSelect,
        KeyboardLeftHanded,
        KeyboardRightHanded,
        KeyboardClassic,
        KeyboardSplit,
        Volume,
        Play,
        Pause,
        ChevronLeft,
        ChevronRight,
        InkingTool,
        Emoji2,
        GripperBarHorizontal,
        System,
        Personalize,
        Devices,
        SearchAndApps,
        Globe,
        TimeLanguage,
        EaseOfAccess,
        UpdateRestore,
        HangUp,
        ContactInfo,
        Unpin,
        Contact,
        Memo,
        Paste,
        PhoneBook,
        LEDLight,
        Error,
        GripperBarVertical,
        Unlock,
        Slideshow,
        Calendar,
        GripperResize,
        Megaphone,
        Trim,
        NewWindow,
        SaveLocal,
        Color,
        DataSense,
        SaveAs,
        Light,
        AspectRatio,
        DataSenseBar,
        Redo,
        Undo,
        Crop,
        OpenWith,
        Rotate,
        SetlockScreen,
        MapPin2,
        Package,
        Warning,
        ReadingList,
        Education,
        ShoppingCart,
        Train,
        Flag,
        Page,
        Multitask,
        BrowsePhotos,
        HalfStarLeft,
        HalfStarRight,
        Record,
        TouchPointer,
        LangJPN,
        Ferry,
        Highlight,
        ActionCenterNotification,
        PowerButton,
        ResizeTouchNarrower,
        ResizeTouchShorter,
        DrivingMode,
        RingerSilent,
        OtherUser,
        Admin,
        CC,
        SDCard,
        CallForwarding,
        SettingsDisplaySound,
        TVMonitor,
        Speakers,
        Headphone,
        DeviceLaptopPic,
        DeviceLaptopNoPic,
        DeviceMonitorRightPic,
        DeviceMonitorLeftPic,
        DeviceMonitorNoPic,
        Game,
        HorizontalTabKey,
        StreetsideSplitMinimize,
        StreetsideSplitExpand,
        Car,
        Walk,
        Bus,
        TiltUp,
        TiltDown,
        RotateMapRight,
        RotateMapLeft,
        Home,
        ParkingLocation,
        MapCompassTop,
        MapCompassBottom,
        IncidentTriangle,
        Touch,
        MapDirections,
        StartPoint,
        StopPoint,
        EndPoint,
        History,
        Location,
        MapLayers,
        Accident,
        Work,
        Construction,
        Recent,
        Bank,
        DownloadMap,
        InkingToolFill2,
        HighlightFill2,
        EraseToolFill,
        EraseToolFill2,
        Dictionary,
        DictionaryAdd,
        ToolTip,
        ChromeBack,
        ProvisioningPackage,
        AddRemoteDevice,
        Ethernet,
        ShareBroadband,
        DirectAccess,
        DialUp,
        DefenderApp,
        BatteryCharging9,
        Battery10,
        Pinned,
        PinFill,
        PinnedFill,
        PeriodKey,
        PuncKey,
        RevToggleKey,
        RightArrowKeyTime1,
        RightArrowKeyTime2,
        LeftQuote,
        RightQuote,
        DownShiftKey,
        UpShiftKey,
        PuncKey0,
        PuncKeyLeftBottom,
        RightArrowKeyTime3,
        RightArrowKeyTime4,
        Battery0,
        Battery1,
        Battery2,
        Battery3,
        Battery4,
        Battery5,
        Battery6,
        Battery7,
        Battery8,
        Battery9,
        BatteryCharging0,
        BatteryCharging1,
        BatteryCharging2,
        BatteryCharging3,
        BatteryCharging4,
        BatteryCharging5,
        BatteryCharging6,
        BatteryCharging7,
        BatteryCharging8,
        BatterySaver0,
        BatterySaver1,
        BatterySaver2,
        BatterySaver3,
        BatterySaver4,
        BatterySaver5,
        BatterySaver6,
        BatterySaver7,
        BatterySaver8,
        SignalBars1,
        SignalBars2,
        SignalBars3,
        SignalBars4,
        SignalBars5,
        SignalNotConnected,
        Wifi1,
        Wifi2,
        Wifi3,
        SIMLock,
        SIMMissing,
        Vibrate,
        RoamingInternational,
        RoamingDomestic,
        CallForwardInternational,
        CallForwardRoaming,
        JpnRomanji,
        JpnRomanjiLock,
        JpnRomanjiShift,
        JpnRomanjiShiftLock,
        StatusDataTransfer,
        StatusDataTransferVPN,
        StatusDualSIM2,
        StatusDualSIM2VPN,
        StatusDualSIM1,
        StatusDualSIM1VPN,
        StatusSGLTE,
        StatusSGLTECell,
        StatusSGLTEDataVPN,
        StatusVPN,
        WifiHotspot,
        LanguageKor,
        LanguageCht,
        LanguageChs,
        USB,
        InkingToolFill,
        View,
        HighlightFill,
        Previous,
        Next,
        Clear,
        Sync,
        Download,
        Help,
        Upload,
        Emoji,
        TwoPage,
        LeaveChat,
        MailForward,
        RotateCamera,
        ClosePane,
        OpenPane,
        PreviewLink,
        AttachCamera,
        ZoomIn,
        Bookmarks,
        Document,
        ProtectedDocument,
        OpenInNewWindow,
        MailFill,
        ViewAll,
        VideoChat,
        Switch,
        Rename,
        Go,
        SurfaceHub,
        Remote,
        Click,
        Shuffle,
        Movies,
        SelectAll,
        Orientation,
        Import,
        ImportAll,
        Folder,
        Webcam,
        Picture,
        Caption,
        ChromeClose,
        ShowResults,
        Message,
        Leaf,
        CalendarDay,
        CalendarWeek,
        Characters,
        MailReplyAll,
        Read,
        ShowBcc,
        HideBcc,
        Cut,
        Copy,
        Important,
        MailReply,
        Sort,
        MobileTablet,
        DisconnectDrive,
        MapDrive,
        ContactPresence,
        Priority,
        GotoToday,
        Font,
        FontColor,
        Contact2,
        FolderFill,
        Audio,
        Permissions,
        DisableUpdates,
        Unfavorite,
        OpenLocal,
        Italic,
        Underline,
        Bold,
        MoveToFolder,
        LikeDislike,
        Dislike,
        Like,
        AlignRight,
        AlignCenter,
        AlignLeft,
        OpenFile,
        ClearSelection,
        FontDecrease,
        FontIncrease,
        FontSize,
        CellPhone,
        Reshare,
        Tag,
        RepeatOne,
        RepeatAll,
        Calculator,
        Directions,
        Library,
        ChatBubbles,
        PostUpdate,
        NewFolder,
        CalendarReply,
        UnsyncFolder,
        SyncFolder,
        BlockContact,
        SwitchApps,
        AddFriend,
        Accept,
        GoToStart,
        BulletedList,
        Scan,
        Preview,
        ZeroBars,
        OneBar,
        TwoBars,
        ThreeBars,
        FourBars,
        World,
        Comment,
        MusicInfo,
        DockLeft,
        DockRight,
        DockBottom,
        Repair,
        Accounts,
        DullSound,
        Manage,
        Street,
        Printer3D,
        RadioBullet,
        Stopwatch,
        Photo,
        ActionCenter,
        FullCircleMask,
        ChromeMinimize,
        ChromeMaximize,
        ChromeRestore,
        Annotation,
        BackSpaceQWERTYSm,
        BackSpaceQWERTYMd,
        Swipe,
        Fingerprint,
        Handwriting,
        ChromeBackToWindow,
        ChromeFullScreen,
        KeyboardStandard,
        KeyboardDismiss,
        Completed,
        ChromeAnnotate,
        Label,
        IBeam,
        IBeamOutline,
        FlickDown,
        FlickUp,
        FlickLeft,
        FlickRight,
        FeedbackApp,
        MusicAlbum,
        Streaming,
        Code,
        ReturnToWindow,
        LightningBolt,
        Info,
        CalculatorMultiply,
        CalculatorAddition,
        CalculatorSubtract,
        CalculatorDivide,
        CalculatorSquareroot,
        CalculatorPercentage,
        CalculatorNegate,
        CalculatorEqualTo,
        CalculatorBackspace,
        Component,
        DMC,
        Dock,
        MultimediaDMS,
        MultimediaDVR,
        MultimediaPMP,
        PrintfaxPrinterFile,
        Sensor,
        StorageOptical,
        Communications,
        Headset,
        Projector,
        Health,
        Webcam2,
        Input,
        Mouse,
        Smartcard,
        SmartcardVirtual,
        MediaStorageTower,
        ReturnKeySm,
        GameConsole,
        Network,
        StorageNetworkWireless,
        StorageTape,
        ChevronUpSmall,
        ChevronDownSmall,
        ChevronLeftSmall,
        ChevronRightSmall,
        ChevronUpMed,
        ChevronDownMed,
        ChevronLeftMed,
        ChevronRightMed,
        Devices2,
        ExpandTile,
        PC1,
        PresenceChicklet,
        PresenceChickletVideo,
        Reply,
        SetTile,
        Type,
        Korean,
        HalfAlpha,
        FullAlpha,
        Key12On,
        ChineseChangjie,
        QWERTYOn,
        QWERTYOff,
        ChineseQuick,
        Japanese,
        FullHiragana,
        FullKatakana,
        HalfKatakana,
        ChineseBoPoMoFo,
        ChinesePinyin,
        ConstructionCone,
        XboxOneConsole,
        Volume0,
        Volume1,
        Volume2,
        Volume3,
        BatteryUnknown,
        WifiAttentionOverlay,
        Robot,
        TapAndSend,
        PasswordKeyShow,
        PasswordKeyHide,
        BidiLtr,
        BidiRtl,
        ForwardSm,
        CommaKey,
        DashKey,
        DullSoundKey,
        HalfDullSound,
        RightDoubleQuote,
        LeftDoubleQuote,
        PuncKeyRightBottom,
        PuncKey1,
        PuncKey2,
        PuncKey3,
        PuncKey4,
        PuncKey5,
        PuncKey6,
        PuncKey9,
        PuncKey7,
        PuncKey8,
        Frigid,
        Diagnostic,
        Process,
        DisconnectDisplay,
        Info2,
        ActionCenterAsterisk,
        Beta,
        SaveCopy,
        List,
        Asterisk,
        ErrorBadge,
        CircleRing,
        CircleFill,
        AllAppsMirrored,
        BookmarksMirrored,
        BulletedListMirrored,
        CallForwardInternationalMirrored,
        CallForwardRoamingMirrored,
        ChromeBackMirrored,
        ClearSelectionMirrored,
        ClosePaneMirrored,
        ContactInfoMirrored,
        DockRightMirrored,
        DockLeftMirrored,
        ExpandTileMirrored,
        GoMirrored,
        GripperResizeMirrored,
        HelpMirrored,
        ImportMirrored,
        ImportAllMirrored,
        LeaveChatMirrored,
        ListMirrored,
        MailForwardMirrored,
        MailReplyMirrored,
        MailReplyAllMirrored,
        OpenPaneMirrored,
        OpenWithMirrored,
        ParkingLocationMirrored,
        ResizeMouseMediumMirrored,
        ResizeMouseSmallMirrored,
        ResizeMouseTallMirrored,
        ResizeTouchNarrowerMirrored,
        SendMirrored,
        SendFillMirrored,
        ShowResultsMirrored,
        Media,
        SyncError,
        Devices3,
        Lightbulb,
        StatusCircle,
        StatusTriangle,
        StatusError,
        StatusWarning,
        Puzzle,
        CalendarSolid,
        HomeSolid,
        ParkingLocationSolid,
        ContactSolid,
        ConstructionSolid,
        AccidentSolid,
        Ringer,
        ThoughtBubble,
        HeartBroken,
        BatteryCharging10,
        BatterySaver9,
        BatterySaver10,
        CallForwardingMirrored,
        MultiSelectMirrored,
        Broom,
        Trackers,
        PieSingle,
        StockDown,
        StockUp,
        Drop,
        BusSolid,
        FerrySolid,
        StartPointSolid,
        StopPointSolid,
        EndPointSolid,
        AirplaneSolid,
        TrainSolid,
        WorkSolid,
        ReminderFill,
        Reminder,
        Heart,
        HeartFill,
        EthernetError,
        EthernetWarning,
        StatusConnecting1,
        StatusConnecting2,
        StatusUnsecure,
        WifiError0,
        WifiError1,
        WifiError2,
        WifiError3,
        WifiError4,
        WifiWarning0,
        WifiWarning1,
        WifiWarning2,
        WifiWarning3,
        WifiWarning4,
        Devices4,
        NUIIris,
        NUIFace,
        EditMirrored,
        NUIFPStartSlideHand,
        NUIFPStartSlideAction,
        NUIFPContinueSlideHand,
        NUIFPContinueSlideAction,
        NUIFPRollRightHand,
        NUIFPRollRightHandAction,
        NUIFPRollLeftHand,
        NUIFPRollLeftAction,
        NUIFPPressHand,
        NUIFPPressAction,
        NUIFPPressRepeatHand,
        NUIFPPressRepeatAction,
        StatusErrorFull,
        MultitaskExpanded,
        Certificate,
        BackSpaceQWERTYLg,
        ReturnKeyLg,
        FastForward,
        Rewind,
        Photo2,
        MobBattery0,
        MobBattery1,
        MobBattery2,
        MobBattery3,
        MobBattery4,
        MobBattery5,
        MobBattery6,
        MobBattery7,
        MobBattery8,
        MobBattery9,
        MobBattery10,
        MobBatteryCharging0,
        MobBatteryCharging1,
        MobBatteryCharging2,
        MobBatteryCharging3,
        MobBatteryCharging4,
        MobBatteryCharging5,
        MobBatteryCharging6,
        MobBatteryCharging7,
        MobBatteryCharging8,
        MobBatteryCharging9,
        MobBatteryCharging10,
        MobBatterySaver0,
        MobBatterySaver1,
        MobBatterySaver2,
        MobBatterySaver3,
        MobBatterySaver4,
        MobBatterySaver5,
        MobBatterySaver6,
        MobBatterySaver7,
        MobBatterySaver8,
        MobBatterySaver9,
        MobBatterySaver10,
        DictionaryCloud,
        ResetDrive,
        VolumeBars,
        Project,
        AdjustHologram,
        WifiCallBars,
        WifiCall0,
        WifiCall1,
        WifiCall2,
        WifiCall3,
        WifiCall4,
        DeviceDiscovery,
        WindDirection,
        RightArrowKeyTime0,
        TabletMode,
        StatusCircleLeft,
        StatusTriangleLeft,
        StatusErrorLeft,
        StatusWarningLeft,
        MobBatteryUnknown,
        NetworkTower,
        CityNext,
        CityNext2,
        Courthouse,
        Groceries,
        Sustainable,
        BuildingEnergy,
        ToggleFilled,
        ToggleBorder,
        SliderThumb,
        ToggleThumb,
        MiracastLogoSmall,
        MiracastLogoLarge,
        PLAP,
        Badge,
        SignalRoaming,
        MobileLocked,
        InsiderHubApp,
        PersonalFolder,
        HomeGroup,
        MyNetwork,
        KeyboardFull,
        MobSignal1,
        MobSignal2,
        MobSignal3,
        MobSignal4,
        MobSignal5,
        MobWifi1,
        MobWifi2,
        MobWifi3,
        MobWifi4,
        MobAirplane,
        MobBluetooth,
        MobActionCenter,
        MobLocation,
        MobWifiHotspot,
        LanguageJpn,
        MobQuietHours,
        MobDrivingMode,
        SpeedOff,
        SpeedMedium,
        SpeedHigh,
        ThisPC,
        MusicNote,
        FileExplorer,
        FileExplorerApp,
        LeftArrowKeyTime0,
        MicOff,
        MicSleep,
        MicError,
        PlaybackRate1x,
        PlaybackRateOther,
        CashDrawer,
        BarcodeScanner,
        ReceiptPrinter,
        MagStripeReader,
        CompletedSolid,
        CompanionApp,
        SwipeRevealArt,
        MicOn,
        MicClipping,
        TabletSelected,
        MobileSelected,
        LaptopSelected,
        TVMonitorSelected,
        DeveloperTools,
        MobCallForwarding,
        MobCallForwardingMirrored,
        BodyCam,
        PoliceCar,
        Draw,
        DrawSolid,
        LowerBrightness,
        ScrollUpDown,
        DateTime,
        Tiles,
        PartyLeader,
        AppIconDefault,
        AddSurfaceHub,
        DevUpdate,
        Unit,
        AddTo,
        RemoveFrom,
        RadioBtnOff,
        RadioBtnOn,
        RadioBullet2,
        ExploreContent,
        ScrollMode,
        ZoomMode,
        PanMode,
        WiredUSB,
        WirelessUSB,
        USBSafeConnect,
        ActionCenterNotificationMirrored,
        ActionCenterMirrored,
        ResetDevice,
        Feedback,
        Subtitles,
        SubtitlesAudio,
        CalendarMirrored,
        eSIM,
        eSIMNoProfile,
        eSIMLocked,
        eSIMBusy,
        SignalError,
        StreamingEnterprise,
        Headphone0,
        Headphone1,
        Headphone2,
        Headphone3,
        KeyboardBrightness,
        KeyboardLowerBrightness,
        SkipBack10,
        SkipForward30,
        TreeFolderFolder,
        TreeFolderFolderFill,
        TreeFolderFolderOpen,
        TreeFolderFolderOpenFill,
        MultimediaDMP,
        KeyboardOneHanded,
        Narrator,
        EmojiTabPeople,
        EmojiTabSmilesAnimals,
        EmojiTabCelebrationObjects,
        EmojiTabFoodPlants,
        EmojiTabTransitPlaces,
        EmojiTabSymbols,
        EmojiTabTextSmiles,
        EmojiTabFavorites,
        EmojiSwatch,
        ConnectApp,
        CompanionDeviceFramework,
        Ruler,
        FingerInking,
        StrokeErase,
        PointErase,
        ClearAllInk,
        Pencil,
        Marker,
        InkingCaret,
        InkingColorOutline,
        InkingColorFill,
        HardDrive,
        NetworkAdapter,
        Touchscreen,
        NetworkPrinter,
        CloudPrinter,
        KeyboardShortcut,
        BrushSize,
        NarratorForward,
        NarratorForwardMirrored,
        SyncBadge12,
        RingerBadge12,
        AsteriskBadge12,
        ErrorBadge12,
        CircleRingBadge12,
        CircleFillBadge12,
        ImportantBadge12,
        MailBadge12,
        PauseBadge12,
        PlayBadge12,
        PenWorkspace,
        Export,
        ExportMirrored,
        CaligraphyPen,
        ReplyMirrored,
        LockscreenDesktop,
        Multitask16,
        Play36,
        PenPalette,
        GuestUser,
        SettingsBattery,
        TaskbarPhone,
        LockScreenGlance,
        ImageExport,
        WifiEthernet,
        ActionCenterQuiet,
        ActionCenterQuietNotification,
        TrackersMirrored,
        DateTimeMirrored,
        Wheel,
        PenWorkspaceMirrored,
        PenPaletteMirrored,
        StrokeEraseMirrored,
        PointEraseMirrored,
        ClearAllInkMirrored,
        BackgroundToggle,
        Marquee,
        Relationship,
        DefaultAPN,
        UserAPN,
        DoublePinyin,
        BlueLight,
        ButtonA,
        ButtonB,
        ButtonY,
        ButtonX,
        ArrowUp8,
        ArrowDown8,
        ArrowRight8,
        ArrowLeft8,
        QuarentinedItems,
        QuarentinedItemsMirrored,
        Protractor,
        ChecklistMirrored,
        StatusCircle7,
        StatusCheckmark7,
        StatusErrorCircle7,
        Connected,
        PencilFill,
        CalligraphyFill,
        QuarterStarLeft,
        QuarterStarRight,
        ThreeQuarterStarLeft,
        ThreeQuarterStarRight,
        QuietHoursBadge12,
        BackMirrored,
        ForwardMirrored,
        ChromeBackContrast,
        ChromeBackContrastMirrored,
        ChromeBackToWindowContrast,
        ChromeFullScreenContrast,
        GridView,
        ClipboardList,
        ClipboardListMirrored,
        OutlineQuarterStarLeft,
        OutlineQuarterStarRight,
        OutlineHalfStarLeft,
        OutlineHalfStarRight,
        OutlineThreeQuarterStarLeft,
        OutlineThreeQuarterStarRight,
        SpatialVolume0,
        SpatialVolume1,
        SpatialVolume2,
        SpatialVolume3,
        OutlineStarLeftHalf,
        OutlineStarRightHalf,
        ChromeAnnotateContrast,
        DefenderBadge12,
        DetachablePC,
        LeftStick,
        RightStick,
        TriggerLeft,
        TriggerRight,
        BumperLeft,
        BumperRight,
        Dpad,
        EnglishPunctuation,
        ChinesePunctuation,
        HMD,
        PaginationDotOutline10,
        PaginationDotSolid10,
        StrokeErase2,
        SmallErase,
        LargeErase,
        FolderHorizontal,
        MicrophoneListening,
        StatusExclamationCircle7,
        StatusCircleOuter,
        StatusCircleInner,
        StatusCircleRing,
        StatusTriangleOuter,
        StatusTriangleInner,
        StatusTriangleExclamation,
        StatusCircleExclamation,
        StatusCircleErrorX,
        StatusCircleCheckmark,
        StatusCircleInfo,
        StatusCircleBlock,
        StatusCircleBlock2,
        StatusCircleQuestionMark,
        StatusCircleSync,
        Dial1,
        Dial2,
        Dial3,
        Dial4,
        Dial5,
        Dial6,
        Dial7,
        Dial8,
        Dial9,
        Dial10,
        Dial11,
        Dial12,
        Dial13,
        Dial14,
        Dial15,
        Dial16,
        DialShape1,
        DialShape2,
        DialShape3,
        DialShape4,
        TollSolid,
        TrafficCongestionSolid,
        ExploreContentSingle,
        CollapseContent,
        CollapseContentSingle,
        InfoSolid,
        GroupList,
        CaretBottomRightSolidCenter8,
        ProgressRingDots,
        Checkbox14,
        CheckboxComposite14,
        CheckboxIndeterminateCombo14,
        CheckboxIndeterminateCombo,
        StatusPause7,
        CharacterAppearance,
        Lexicon,
        ScreenTime,
        HeadlessDevice,
        NetworkSharing,
        WindowsInsider,
        ChromeSwitch,
        ChromeSwitchContast,
        StatusCheckmark,
        StatusCheckmarkLeft,
        KeyboardLeftAligned,
        KeyboardRightAligned,
        KeyboardSettings,
        IOT,
        ExploitProtectionSettings,
        KeyboardNarrow,
        Keyboard12Key,
        KeyboardDock,
        KeyboardUndock,
        KeyboardLeftDock,
        KeyboardRightDock,
        Ear,
        PointerHand,
        Bullseye,
        PassiveAuthentication,
        NetworkOffline,
        NetworkConnected,
        NetworkConnectedCheckmark
    }
}